version: '3.8'

services:
  postgres:
    image: postgres
    container_name: graphql_security_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_security
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
